import Head from 'next/head'
import { Inter } from 'next/font/google'
import Button from '@/components/Button/'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cingulata</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <h1>Test</h1>
        <p>right now the index page is just a testing zone for new components</p>
        <Button icon="star" onclick={() => { alert("this is an alert") }} style="primary">Click me</Button>
      </main>
    </>
  )
}
