import Head from 'next/head'
import Button from '@/components/Button/'
import { Dispatch, SetStateAction, useEffect, useState } from 'react'
import Modal from '@/components/Modal'
import { client } from './_app'
import { EntityTypes } from '@/lib/api/managers/ContentManager'
import Styling from "@/styles/pages/index.module.css"
import Icon, { IconType } from '@/components/Icon'
import Link from 'next/link'


type DockItem = {
  icon: IconType,
  href: string,
  label: string,
  selected?: boolean
}

export function Dock( { items }: { items: DockItem[] } ) {

  const [ selected, setSelected ] = useState("")

  useEffect(() => {
    const path = window.location.pathname.split("/")
    setSelected(`/${path[1]}`)
  })

  return (
    <nav role="navigation" aria-label="Navbar" className={Styling.nav}>
      { items.map(i => <div key={i.label} className={`${Styling.nav_item} ${i.href === selected ? Styling.selected : ""}`}> <Link onClick={() => { setSelected(i.href) }} className={Styling.link_item} key={i.href} href={i.href}> <Icon className={Styling.icon} type={i.icon} /> <p className={Styling.label}>{i.label}</p> </Link></div>) }
    </nav>
  )
}


export default function Home() {

  const [ modal, showModal ] = useState(false)
  const [ disabled, setDisabled ] = useState(false)

  useEffect(() => {
    client.content.getChildren("root")
      .then(c => {
        console.log(c)
      })
  }, [])

  return (
    <>
      <Head>
        <title>Cingulata</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </>
  )
}
